import type { Metadata } from "next";
import { Quicksand, Cookie } from "next/font/google";
import "./globals.css";
import SiteShell from "@/components/SiteShell"; 

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "600"],
  display: "swap",
});

const cookie = Cookie({
  subsets: ["latin"],
  variable: "--font-display",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Quitute Doce Desejo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${quicksand.variable} ${cookie.variable}`}
    >
      <body className="bg-white min-h-screen">
        <SiteShell>{children}</SiteShell>
      </body>
    </html>
  );
}
